from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic.base import RedirectView
from . import views
from . import WebViews, HomeViews, PropertyViews, ContentViews, ReportViews, MemberViews, EnquiryViews, SystemViews, \
    MaintenanceViews

urlpatterns = [
    # View path
    path('cms', views.login, name="login"),
    path('login', views.login, name="login"),
    path('doLogin/', views.doLogin, name="doLogin"),
    path('checkLogin/', views.checkLogin, name="checkLogin"),
    path('logout', views.logout, name="logout"),
    path('accessdenied/', views.accessdenied, name="accessdenied"),
    path('undercon/', views.undercon, name="undercon"),

    # Web path
    path('', WebViews.main, name="main"),
    path('main/', WebViews.main, name="main"),
    path('main_response/', WebViews.main_response, name="main_response"),
    path('about/', WebViews.about, name="about"),
    path('terms/', WebViews.terms, name="terms"),
    path('disclaimer/', WebViews.disclaimer, name="disclaimer"),
    path('privacy/', WebViews.privacy, name="privacy"),
    path('news/', WebViews.news, name="news"),
    path('news/<str:date_id>', WebViews.news, name="news"),
    path('news_detail/', WebViews.news_detail, name="news_detail"),
    path('news_detail/<news_id>', WebViews.news_detail, name="news_detail"),
    path('news_response/', WebViews.news_response, name="news_response"),
    path('oversea/', WebViews.oversea, name="oversea"),
    path('account/', WebViews.account, name="account"),
    path('account_save/', WebViews.account_save, name="account_save"),
    path('contact/', WebViews.contact, name="contact"),
    path('entrust/', WebViews.entrust, name="entrust"),
    path('entrust_save/', WebViews.entrust_save, name="entrust_save"),
    path('mortgage/', WebViews.mortgage, name="mortgage"),
    path('mortgage_response/', WebViews.mortgage_response, name="mortgage_response"),
    path('mortgage_save/', WebViews.mortgage_save, name="mortgage_save"),
    path('property_add/', WebViews.property_add, name="property_add"),
    # path('property_add/<property_id>', WebViews.property_add, name="property_add"),
    path('property_show/<property_id>', WebViews.property_show, name="property_show"),
    path('property_preview/<property_id>', WebViews.property_preview, name="property_preview"),
    path('enquiry_save/', WebViews.enquiry_save, name="enquiry_save"),
    path('property_search/', WebViews.property_search, name="property_search"),
    path('property_data/', WebViews.property_data, name="property_data"),
    path('property_search/<str:propertyname>', WebViews.property_search, name="property_search"),
    path('property_search/<str:propertyname>/<str:usage>', WebViews.property_search, name="property_search"),
    path('property_search/<str:propertyname>/<str:usage>/<str:district>', WebViews.property_search,
         name="property_search"),
    path('property_foreign_search/', WebViews.property_foreign_search, name="property_foreign_search"),
    path('property_foreign_data/', WebViews.property_foreign_data, name="property_foreign_data"),
    path('property_foreign_show/<property_foreign_id>', WebViews.property_foreign_show, name="property_foreign_show"),
    path('property_foreign_preview/<property_foreign_id>', WebViews.property_foreign_preview,
         name="property_foreign_preview"),
    path('newproperty/', WebViews.newproperty, name="newproperty"),
    path('newproperty_show/<listing_id>', WebViews.newproperty_show, name="newproperty_show"),
    path('search_result/', WebViews.search_result, name="search_result"),
    path('transaction/', WebViews.transaction, name="transaction"),
    path('favourite/', WebViews.favourite, name="favourite"),
    path('favourite_data/', WebViews.favourite_data, name="favourite_data"),
    path('common/', WebViews.common, name="common"),
    path('logoutw', WebViews.logoutw, name="logoutw"),

    path('form_visittour/', WebViews.form_visittour, name="form_visittour"),
    path('form_visittour_save/', WebViews.form_visittour_save, name="form_visittour_save"),

    # Home path
    path('home/', HomeViews.home, name="home"),
    path('home_response/', HomeViews.home_response, name="home_response"),
    path('home3/', HomeViews.home3, name="home3"),
    path('home_response_3/', HomeViews.home_response_3, name="home_response_3"),
    path('outDated/', HomeViews.outDated, name="outDated"),

    # Property path
    path('property/', PropertyViews.property, name="property"),
    path('property/<propertyid>', PropertyViews.property, name="property"),
    path('property_response/', PropertyViews.property_response, name="property_response"),
    path('property_save/', PropertyViews.property_save, name="property_save"),
    path('newPropertyMain/', PropertyViews.newPropertyMain, name="newPropertyMain"),
    path('newPropertyMain/<propertyid>', PropertyViews.newPropertyMain, name="newPropertyMain"),
    path('newPropertyMain_response/', PropertyViews.newPropertyMain_response, name="newPropertyMain_response"),
    path('newPropertyMain_save/', PropertyViews.newPropertyMain_save, name="newPropertyMain_save"),
    path('foreignPropertyMain/', PropertyViews.foreignPropertyMain, name="foreignPropertyMain"),
    path('foreignPropertyMain/<propertyid>', PropertyViews.foreignPropertyMain, name="newPropertyMain"),
    path('foreignPropertyMain_response/', PropertyViews.foreignPropertyMain_response,
         name="foreignPropertyMain_response"),
    path('foreignPropertyMain_save/', PropertyViews.foreignPropertyMain_save, name="foreignPropertyMain_save"),
    path('ownerMain/', PropertyViews.ownerMain, name="ownerMain"),
    path('ownerMain_response/', PropertyViews.ownerMain_response, name="ownerMain_response"),
    path('residential/', PropertyViews.residential, name="residential"),
    path('office/', PropertyViews.office, name="office"),
    path('shop/', PropertyViews.shop, name="shop"),
    path('industrial/', PropertyViews.industrial, name="industrial"),
    path('carpark/', PropertyViews.carpark, name="carpark"),
    path('upload_property/', PropertyViews.upload_property, name="upload_property"),
    path('upload_newproperty/', PropertyViews.upload_newproperty, name="upload_newproperty"),
    path('upload_foreignproperty/', PropertyViews.upload_foreignproperty, name="upload_foreignproperty"),
    path('upload/', PropertyViews.upload, name="upload"),
    path('upload_foreign/', PropertyViews.upload_foreign, name="upload_foreign"),
    path('upload_newproperty/', PropertyViews.upload_newproperty, name="upload_newproperty"),
    path('oddsheet/', PropertyViews.oddsheet, name="oddsheet"),
    path('oddsheet_response/', PropertyViews.oddsheet_response, name="oddsheet_response"),
    path('oddsheet_download/<propertyid>', PropertyViews.oddsheet_download, name="oddsheet_download"),
    path('oddsheet_download_all/<propertyid>', PropertyViews.oddsheet_download_all, name="oddsheet_download_all"),
    path('download_oddsheet_excel/', PropertyViews.download_oddsheet_excel, name="download_oddsheet_excel"),
    path('download_oddsheet_image/', PropertyViews.download_oddsheet_image, name="download_oddsheet_image"),
    path('offer/', PropertyViews.offer, name="offer"),
    path('offer_response/', PropertyViews.offer_response, name="offer_response"),
    path('offer_download/<propertyid>', PropertyViews.offer_download, name="offer_download"),

    # Web-Content path
    path('about_main/', ContentViews.about_main, name="about_main"),
    path('about_main_response/', ContentViews.about_main_response, name="about_main_response"),
    path('terms_main/', ContentViews.terms_main, name="terms_main"),
    path('terms_main_response/', ContentViews.terms_main_response, name="terms_main_response"),
    path('disclaimer_main/', ContentViews.disclaimer_main, name="disclaimer_main"),
    path('disclaimer_main_response/', ContentViews.disclaimer_main_response, name="disclaimer_main_response"),
    path('privacy_main/', ContentViews.privacy_main, name="privacy_main"),
    path('privacy_main_response/', ContentViews.privacy_main_response, name="privacy_main_response"),
    path('news_main/', ContentViews.news_main, name="news_main"),
    path('news_main_response/', ContentViews.news_main_response, name="news_main_response"),

    # Report path

    # Enquiry path
    path('entrustMain/', EnquiryViews.entrustMain, name="entrustMain"),
    path('entrustMain_response/', EnquiryViews.entrustMain_response, name="entrustMain_response"),
    path('entrustMain_save/', EnquiryViews.entrustMain_save, name="entrustMain_save"),
    path('mortgageRefer/', EnquiryViews.mortgageRefer, name="mortgageRefer"),
    path('mortgageRefer_response/', EnquiryViews.mortgageRefer_response, name="mortgageRefer_response"),
    path('mortgageRefer_save/', EnquiryViews.mortgageRefer_save, name="mortgageRefer_save"),
    path('onlineEnquiry/', EnquiryViews.onlineEnquiry, name="onlineEnquiry"),
    path('onlineEnquiry_response/', EnquiryViews.onlineEnquiry_response, name="onlineEnquiry_response"),
    path('onlineEnquiry_save/', EnquiryViews.onlineEnquiry_save, name="onlineEnquiry_save"),

    path('propertyEnquiry/', EnquiryViews.propertyEnquiry, name="propertyEnquiry"),
    path('propertyEnquiry/<selectType>/', EnquiryViews.propertyEnquiry, name="propertyEnquiry"),
    path('propertyEnquiry_response/', EnquiryViews.propertyEnquiry_response, name="propertyEnquiry_response"),
    path('propertyEnquiry_save/', EnquiryViews.propertyEnquiry_save, name="propertyEnquiry_save"),

    path('logEnquiry/', EnquiryViews.logEnquiry, name="logEnquiry"),
    path('logEnquiry_response/', EnquiryViews.logEnquiry_response, name="logEnquiry_response"),
    path('logEnquiry_save/', EnquiryViews.logEnquiry_save, name="logEnquiry_save"),
    path('logEnquiryResponse_save/', EnquiryViews.logEnquiryResponse_save, name="logEnquiryResponse_save"),

    # Member path
    path('member/', MemberViews.member, name="member"),
    path('member_response/', MemberViews.member_response, name="member_response"),
    path('customerNote/', MemberViews.customerNote, name="customerNote"),
    path('customerNote_response/', MemberViews.customerNote_response, name="customerNote_response"),
    path('customerNote_save/', MemberViews.customerNote_save, name="customerNote_save"),

    # System path
    path('sidebar/', SystemViews.sidebar, name="sidebar"),
    path('sidebar1/', SystemViews.sidebar, name="sidebar1"),

    path('userList/', SystemViews.userList, name="userList"),
    path('userList_response/', SystemViews.userList_response, name="userList_response"),
    path('accessRight/', SystemViews.accessRight, name="accessRight"),
    path('accessRight_response/', SystemViews.accessRight_response, name="accessRight_response"),
    path('systemTab/', SystemViews.systemTab, name="systemTab"),
    path('systemTab_response/', SystemViews.systemTab_response, name="systemTab_response"),
    path('category/', SystemViews.category, name="category"),
    path('category_response/', SystemViews.category_response, name="category_response"),
    path('subCategory/', SystemViews.subCategory, name="subCategory"),
    path('subCategory_response/', SystemViews.subCategory_response, name="subCategory_response"),
    path('userLog/', SystemViews.userLog, name="userLog"),
    path('userLog_response/', SystemViews.userLog_response, name="userLog_response"),
    path('printer/', SystemViews.printer, name="printer"),
    path('printer_response/', SystemViews.printer_response, name="printer_response"),
    path('printer2/', SystemViews.printer2, name="printer2"),
    path('printer_response_2/', SystemViews.printer_response_2, name="printer_response_2"),

    # Maintenance path
    path('shopList/', MaintenanceViews.shopList, name="shopList"),
    path('shopList_response/', MaintenanceViews.shopList_response, name="shopList_response"),

    path('possession/', MaintenanceViews.possession, name="possession"),
    path('possession_response/', MaintenanceViews.possession_response, name="possession_response"),
    path('district/', MaintenanceViews.district, name="district"),
    path('district_response/', MaintenanceViews.district_response, name="district_response"),
    path('subdistrict/', MaintenanceViews.subdistrict, name="subdistrict"),
    path('subdistrict_response/', MaintenanceViews.subdistrict_response, name="subdistrict_response"),
    path('street/', MaintenanceViews.street, name="street"),
    path('street_response/', MaintenanceViews.street_response, name="street_response"),
    path('usage/', MaintenanceViews.usage, name="usage"),
    path('usage_response/', MaintenanceViews.usage_response, name="usage_response"),

    path('watermark_gen/', MaintenanceViews.watermark_gen, name="watermark_gen"),
    path('transaction_cap/', MaintenanceViews.transaction_cap, name="transaction_cap"),
    path('transaction_cap/<str:transaction_type>', MaintenanceViews.transaction_cap, name="transaction_cap"),
    path('transaction_cap_office/', MaintenanceViews.transaction_cap_office, name="transaction_cap_office"),
    path('transaction_cap_industrial/', MaintenanceViews.transaction_cap_industrial, name="transaction_cap_industrial"),
    path('transaction_cap_shop/', MaintenanceViews.transaction_cap_shop, name="transaction_cap_shop"),

    path('testingPage/', MaintenanceViews.testingPage, name="testingPage"),
    path('testingPage_response/', MaintenanceViews.testingPage_response, name="testingPage_response"),

    # path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),),
]
